plugins { id 'base' }

subprojects {
    apply plugin: 'java-library'
    group = 'cc.sirrus.ysmlib'
    version = '0.1.0'
    repositories { mavenCentral() }
    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        withSourcesJar()
    }
    tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
    dependencies {
        testImplementation platform('org.junit:junit-bom:5.11.4')
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }
    test { useJUnitPlatform() }
}

tasks.named('build') { dependsOn subprojects.collect { it.tasks.named('build') } }
tasks.named('check') { dependsOn subprojects.collect { it.tasks.named('check') } }
