plugins {
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}
dependencies {
    implementation project(':ysm-runtime-v3d')
    implementation project(':ysm-runtime-java-v3')
}
application { mainClass = 'cc.sirrus.ysmlib.tools.V3dTool' }
processResources {
    from(rootProject.file('../LICENSE'))
    from(rootProject.file('forge/src/main/resources/licenses/aircompressor-0.27')) {
        into 'licenses/aircompressor-0.27'
    }
}
jar { archiveClassifier = 'thin' }
shadowJar {
    archiveClassifier = ''
    manifest { attributes 'Main-Class': application.mainClass.get() }
    relocate 'com.google.gson', 'cc.sirrus.ysmlib.internal.gson'
    relocate 'io.airlift.compress', 'cc.sirrus.ysmlib.internal.aircompressor'
    exclude 'META-INF/*.SF', 'META-INF/*.RSA', 'META-INF/*.DSA'
    exclude 'module-info.class', 'META-INF/versions/**'
}
assemble.dependsOn shadowJar
